### PR TITLE
Test email notifications

### PR DESCRIPTION
**Pull request by arthuroe**
Tests for all requests related to emails.

### CODE REVIEW

**Comment by nateklaiber** [comment]
@arthuroe - Question for you. 

If I run all of the unit tests, I get:

```
python -m unittest tests
```
Results: 
```
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

If I try and run a single test in isolation I get errors:

```
======================================================================
ERROR: test_retrieve (tests.test_requests_email_notifications.TestRequestsEmailNotifications)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/www/naas-api-client-python/tests/test_requests_email_notifications.py", line 38, in test_retrieve
    'data']['id']
KeyError: 'id'

----------------------------------------------------------------------
Ran 6 tests in 1.855s

FAILED (errors=4)
```

Is this expected?

I typically run tests:

* In random order - to ensure nothing requires specific order dependencies
* Of a specific tests - I specify the test and line number of the test
* Of a specific test file - I specify the file and run the test while working on the code
* Of an entire suite - run all tests

**Comment by arthuroe** [comment]
@nateklaiber the command runs fine on mine. Getting @muhallan to run on his.
You need to set these in your .env
`TEST_PORT= 'port'`
`TEST_PASSWORD='password'`
`TEST_EMAIL='email'`

**Comment by arthuroe** [comment]
Let me update the `.env.sample`

**Comment by nateklaiber** [comment]
@arthuroe - that was it! I added the `env` vars and it passed. Thank you!

**Comment by nateklaiber** [comment]
@arthuroe - only thing I see when running the entire suite is a single failure in the tests:
```
FAIL: test_create_missing_parameters_unsuccessful (tests.test_requests_projects.TestRequestsProjects)
```

**Comment by arthuroe** [comment]
@nateklaiber when I run `python -m unittest`
```
.................................................................
----------------------------------------------------------------------
Ran 65 tests in 470.988s

OK
```

**Comment by nateklaiber** [comment]
@arthuroe - disregard my last note, this was a test I had put in place (and will add back in once the first release was out). This was me testing to see how it handled invalid parameters passed as arguments. Going to merge in now!

**Pull request merged**
